refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{l}] ({M}) {m}{n}"

  file:
    kind: rolling_file
    path: "logs/oobe.log"
    policy:
      kind: size
      limit: 1mb
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{l}] {m}{n}"

root:
  level: info
  appenders:
    - stdout
    - file

loggers:
  common:
    level: debug
    appenders:
      - stdout
    additive: false

  oobe_engine:
    level: debug
    appenders:
      - stdout
      - file
    additive: false
