[package]
name = "plugin_example_1"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }

[lib]
crate-type = ["cdylib"]