[package]
name = "oobe_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
tokio = { version = "1", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
